// Code generated by ntaps. DO NOT EDIT.
package application

import (
	"github.com/pkg/errors"

	"github.com/tiket/learn-crud/application/pegawai"

	"go.uber.org/dig"
)

func Register(container *dig.Container) error {

	// - pegawai-domain-start
	if err := container.Provide(pegawai.NewService); err != nil {
		return errors.Wrap(err, "failed to provide pegawai app service")
	}
	// - pegawai-domain-end

	// - pegawai-pegawai-repository-start
	if err := container.Provide(pegawai.NewPegawaiRepository); err != nil {
		return errors.Wrap(err, "failed to provide pegawai repository")
	}
	// - pegawai-pegawai-repository-end

	// application-di-end

	return nil
}
