// Code generated by ntaps. DO NOT EDIT.
package application

import (
	"go.uber.org/dig"

	"github.com/tiket/learn-crud/application/pegawai"
)

type (
	Holder struct {
		dig.In

		// - pegawai-domain-start
		PegawaiService pegawai.Service
		// - pegawai-domain-end

		// - application-holder-end
	}
)
