// Code generated by ntaps. DO NOT EDIT.
package pegawai

import (
	"github.com/tiket/learn-crud/interfaces"
	"github.com/tiket/learn-crud/shared"
)

type (
	Controller struct {
		SharedHolder     shared.Holder
		InterfacesHolder interfaces.Holder
	}
)

func NewController(sh shared.Holder, ih interfaces.Holder) (*Controller, error) {
	return &Controller{sh, ih}, nil
}
