// Code generated by ntaps. DO NOT EDIT.
package di

import (
	"github.com/pkg/errors"
	"github.com/tiket/learn-crud/application"
	"github.com/tiket/learn-crud/infrastructure"
	"github.com/tiket/learn-crud/interfaces"
	"github.com/tiket/learn-crud/shared"
	"go.uber.org/dig"
)

var (
	Container *dig.Container = dig.New()
)

func init() {
	if err := application.Register(Container); err != nil {
		panic(errors.Wrap(err, "failed to register application container"))
	}

	if err := interfaces.Register(Container); err != nil {
		panic(errors.Wrap(err, "failed to register interfaces container"))
	}

	if err := infrastructure.Register(Container); err != nil {
		panic(errors.Wrap(err, "failed to register infrastructure container"))
	}

	if err := shared.Register(Container); err != nil {
		panic(errors.Wrap(err, "failed to register shared container"))
	}
}
