// Code generated by ntaps. DO NOT EDIT.
package di

import (
	"github.com/pkg/errors"

	"github.com/tiket/TIX-HOTEL-UTILITIES-GO/logs"

	migrator "github.com/tiket/TIX-HOTEL-UTILITIES-GO/util/migration"

	"github.com/tiket/TIX-HOTEL-UTILITIES-GO/persistent"

	"github.com/tiket/learn-crud/migration"
)

func NewMigration(orm persistent.ORM, logger logs.Logger) (migrator.Tool, error) {
	scripts := migration.MigrationScript
	return migrator.NewSqlMigration(orm, scripts, logger)
}

func init() {
	if err := Container.Provide(NewMigration); err != nil {
		panic(errors.Wrap(err, "failed to provide postgres-migration-kit"))
	}
}
