// Code generated by ntaps. DO NOT EDIT.
package di

import (
	"github.com/pkg/errors"

	validator "github.com/tiket/TIX-HOTEL-UTILITIES-GO/util/validator"
)

func NewValidator() (validator.Validator, error) {
	return validator.New(), nil
}

func init() {
	if err := Container.Provide(NewValidator); err != nil {
		panic(errors.Wrap(err, "failed to provide validator"))
	}
}
