// Code generated by MockGen. DO NOT EDIT.
// Source: application/pegawai/service.go

package pegawai

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	pegawai "github.com/tiket/learn-crud/shared/dto/pegawai"
	reflect "reflect"
)

// MockService is a mock of Service interface
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// GetAllPegawai mocks base method
func (m *MockService) GetAllPegawai(ctx context.Context, request pegawai.GetAllPegawaiRequestDto) (*pegawai.GetAllPegawaiResponseDto, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllPegawai", ctx, request)
	ret0, _ := ret[0].(*pegawai.GetAllPegawaiResponseDto)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllPegawai indicates an expected call of GetAllPegawai
func (mr *MockServiceMockRecorder) GetAllPegawai(ctx, request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllPegawai", reflect.TypeOf((*MockService)(nil).GetAllPegawai), ctx, request)
}

// UpdatePegawai mocks base method
func (m *MockService) UpdatePegawai(ctx context.Context, request pegawai.UpdatePegawaiRequestDto) (*pegawai.UpdatePegawaiResponseDto, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePegawai", ctx, request)
	ret0, _ := ret[0].(*pegawai.UpdatePegawaiResponseDto)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePegawai indicates an expected call of UpdatePegawai
func (mr *MockServiceMockRecorder) UpdatePegawai(ctx, request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePegawai", reflect.TypeOf((*MockService)(nil).UpdatePegawai), ctx, request)
}

// CreatePegawai mocks base method
func (m *MockService) CreatePegawai(ctx context.Context, request pegawai.CreatePegawaiRequestDto) (*pegawai.CreatePegawaiResponseDto, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePegawai", ctx, request)
	ret0, _ := ret[0].(*pegawai.CreatePegawaiResponseDto)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePegawai indicates an expected call of CreatePegawai
func (mr *MockServiceMockRecorder) CreatePegawai(ctx, request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePegawai", reflect.TypeOf((*MockService)(nil).CreatePegawai), ctx, request)
}

// DeletePegawai mocks base method
func (m *MockService) DeletePegawai(ctx context.Context, request pegawai.DeletePegawaiRequestDto) (*pegawai.DeletePegawaiResponseDto, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePegawai", ctx, request)
	ret0, _ := ret[0].(*pegawai.DeletePegawaiResponseDto)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeletePegawai indicates an expected call of DeletePegawai
func (mr *MockServiceMockRecorder) DeletePegawai(ctx, request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePegawai", reflect.TypeOf((*MockService)(nil).DeletePegawai), ctx, request)
}
