// Code generated by ntaps. DO NOT EDIT.
package shared

import (
	"github.com/pkg/errors"
	"github.com/tiket/learn-crud/shared/config"
	"go.uber.org/dig"
)

func Register(container *dig.Container) error {
	if err := container.Provide(config.NewEnvConfiguration); err != nil {
		return errors.WithStack(err)
	}

	if err := RegisterCustomHolder(container); err != nil {
		return errors.WithStack(err)
	}

	return nil
}
