// Code generated by ntaps. DO NOT EDIT.
package interfaces

import (
	"github.com/pkg/errors"

	"github.com/tiket/learn-crud/interfaces/pegawai"

	"go.uber.org/dig"
)

func Register(container *dig.Container) error {

	// - pegawai-view-service-start
	if err := container.Provide(pegawai.NewViewService); err != nil {
		return errors.Wrap(err, "failed to provide pegawai app service")
	}
	// - pegawai-view-service-end

	// - interfaces-di-end

	return nil
}
